# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

PBasis <- function(data, basis, intercept, n_terms, reccur_limit) {
    .Call('OptionPrice_PBasis', PACKAGE = 'OptionPrice', data, basis, intercept, n_terms, reccur_limit)
}

LBasis <- function(data, basis, intercept, n_terms, reccur_limit) {
    .Call('OptionPrice_LBasis', PACKAGE = 'OptionPrice', data, basis, intercept, n_terms, reccur_limit)
}

BermudaPutLSM <- function(path, strike, discount, basis, intercept, basis_type) {
    .Call('OptionPrice_BermudaPutLSM', PACKAGE = 'OptionPrice', path, strike, discount, basis, intercept, basis_type)
}

